version: '3.8'

services:
  db:
    image: postgres:13.5
    container_name: stayup-db
    restart: on-failure
    environment:
      POSTGRES_DB: stayup_db
      POSTGRES_USER: stayup
      POSTGRES_PASSWORD: upstay
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - stayup-net
  stayup-api:
    image: local/stayup-api:latest
    container_name: stayup-api
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: stayup
      DB_PASS: upstay
      SERVICE_REFRESH_TIME_MS: 2500
    ports:
      - 5555:5555
    networks:
      - stayup-net
    depends_on:
      - db
  stayup-client:
    image: local/stayup-client:latest
    container_name: stayup-client
    restart: on-failure
    ports:
      - 80:3000
    networks:
      - stayup-net
    depends_on:
      - db
      - stayup-api

networks:
  stayup-net:
    driver: bridge
volumes:
  db_data:
