version: '3.8'

services:
  # Nginx reverse-proxy for routing traffic to server resources (NOTE: Ensure networks are first connected for any services configured in nginx.conf)
  webserver:
    image: nginx:1.21.0-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html # Volume mount for web-root (optional)
      - ./.docker/nginx:/etc/nginx/conf.d # Volume mount for nginx config folder (required)
      - ./.docker/nginx/snippets:/config/nginx # Volume mount for some nginx config snippets (required)
      - ./.docker/ssl/certs:/ssl/certs
      - ./.docker/ssl/private:/ssl/private
    ports:
      - 80:80
      - 443:443
    depends_on:
      - redis
      - stayup-api
      - stayup-client
    networks:
      - stayup-net
  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - stayup-net
  stayup-api:
    image: sykeben/stayup-api:2.0.1
    container_name: stayup-api
    restart: on-failure
    environment:
      REDIS_RDB_HOST: redis
      REDIS_RDB_PORT: 6379
      SERVICE_REFRESH_TIME_MS: 2500
    ports:
      - 5555:5555
    networks:
      - stayup-net
    depends_on:
      - redis
  stayup-client:
    image: sykeben/stayup-client:2.0.0
    container_name: stayup-client
    restart: on-failure
    environment:
      API_BASE_URL: https://status.sykeshome.io/api
      API_WEBSOCK_URL: wss://status.sykeshome.io/api/service/ws
    networks:
      - stayup-net
    depends_on:
      - redis
      - stayup-api

networks:
  stayup-net:
    driver: bridge
volumes:
  redis_data:
  web-root:
    driver: local
