name: Deploy Docker

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get Project Version
        id: project_info
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
      - name: Split Package Version
        id: version_split
        uses: JungWinter/split@v1.1.0
        with:
          msg: ${{ steps.project_info.outputs.version }}
          seperator: '.'
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_ID }}/stayup-api:${{ steps.project_info.outputs.version }}
            ${{ secrets.DOCKER_ID }}/stayup-api:${{ steps.version_split.outputs._0 }}.x
            ${{ secrets.DOCKER_ID }}/stayup-api:${{ steps.version_split.outputs._0 }}.${{ steps.version_split.outputs._1 }}.x
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}